name: pytest
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  pytest:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.7.7
          uses: actions/setup-python@v2
          with:
            python-version: '3.7.7'
        - name: Install Poetry
          uses: snok/install-poetry@v1.1.1
          with:
            virtualenvs-create: true
            virtualenvs-in-project: true
        - name: Install dependencies
          run: poetry install -E optionals
        - name: Run tests
          run: poetry run pytest